export const SET_CURRENT = 'SET_CURRENT';
export const SET_MESSAGES = 'SET_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_USERCHAT = 'ADD_USERCHAT';
export const REMOVE_USERCHAT = 'REMOVE_USERCHAT';
